# syntax=docker/dockerfile:experimental

FROM python:3.10.1

ARG PROJECT_NAME

COPY requirements.txt /$PROJECT_NAME/requirements.txt
COPY requirements-dev.txt /$PROJECT_NAME/requirements-dev.txt
RUN pip install --upgrade pip
RUN --mount=type=cache,target=/root/.cache/pip pip install -r /$PROJECT_NAME/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip pip install -r /$PROJECT_NAME/requirements-dev.txt

COPY . /$PROJECT_NAME

WORKDIR /$PROJECT_NAME
