service: cloudwatch-sns-to-slack

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: python3.8
  timeout: 60
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/*"
    - Effect: Allow
      Action:
        - s3:putObject
      Resource: "arn:aws:s3:::com.legiti.cloudwatch-slack-alerts/*"

custom:
  pythonRequirements:
    slim: true

functions:
  cloudwatch-sns-to-slack:
    handler: cloudwatch_sns_to_slack/handler.handler
    name: cloudwatch-sns-to-slack
    description: Reads messages posted to SNS by Cloudwatch and publish them to the appropriate Slack channel
    runtime: python3.8
    environment:
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
      RUNNING_IN_PROD: true
    package:
      exclude:
        - ./** # We are excluding everything and then only including what we need so we reduce our lambda size
      include:
        - cloudwatch_sns_to_slack/**/*.py
    events: # need to add each channel manually; should be created in Canaveral beforehand
      - sns: ${ssm:/cloudwatch_sns_to_slack/apps-alerts}
      - sns: ${ssm:/cloudwatch_sns_to_slack/area-51-aws} # delete after https://github.com/legiti/canaveral/pull/467 is applied/merges
      - sns: ${ssm:/cloudwatch_sns_to_slack/integration-alerts}
      - sns: ${ssm:/cloudwatch_sns_to_slack/mlplatform-alerts}
      - sns: ${ssm:/cloudwatch_sns_to_slack/modelagem-alerts-ec2}
      - sns: ${ssm:/cloudwatch_sns_to_slack/sre-alerts}
      - sns: ${ssm:/cloudwatch_sns_to_slack/data-quality-alerts}
      - sns: ${ssm:/cloudwatch_sns_to_slack/platform-alerts}
      - sns: ${ssm:/cloudwatch_sns_to_slack/test_channel}
