orbs:
  serverless-deploy: legiti-tests/serverless-deploy@0.0.21

version: 2.1

jobs:
  lint-unit-test-integration-test:
    docker:
      - image: circleci/python:3.8.5
        auth:
          username: legiti
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - run:
          name: Build
          command: |
            make docker-build-test-image
      - run:
          name: Lint
          command: |
            make lint
      - run:
          name: Unit Tests
          command: |
            make unit-test
      - run:
          name: Integration Tests
          command: |
            make integration-test

workflows:
  lint-unit-test-integration-test:
    jobs:
      - lint-unit-test-integration-test:
          filters:
            branches:
              ignore:
                - main
  deploy:
    jobs:
      - serverless-deploy/deploy:
          name: deploy
          production: true
          application-name: 'cloudwatch-sns-to-slack'
          python-version: '3.8'
          filters:
            branches:
              only:
                - main