orbs:
  legiti-slack: legiti-tests/legiti-slack-messages@0.0.4
  node: circleci/node@2.0.3
  serverless: circleci/serverless-framework@1.0.1

version: 2.1

jobs:
  deploy:
      description: |
        Uses Serverless framework to deploy the most recent build
      docker:
        - image: nikolaik/python-nodejs:python3.8-nodejs14
          auth:
            username: legiti
            password: $DOCKERHUB_PASSWORD
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - serverless/setup:
            app-name: cloudwatch-sns-to-slack
            org-name: legiti
        - run:
            command: npm install
            name: npm install
        - run:
            command: serverless deploy --stage prod
            name: Deploying new service version
        - legiti-slack/deploy-success:
            service-name: cloudwatch-sns-to-slack-lambda
            environment: prod
        - legiti-slack/deploy-failure: # only sends message on failure
            service-name: cloudwatch-sns-to-slack-lambda
            environment: prod
  lint-and-run-unit-tests:
    docker:
      - image: circleci/python:3.8.5
        auth:
          username: legiti
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - run:
          name: Build test image
          command: |
            make docker-build-test-image
      - run:
          name: Run linting
          command: |
            make lint
      - run:
          name: Run unit tests
          command: |
            make unit-test

workflows:
  lint-and-run-unit-tests:
    jobs:
      - lint-and-run-unit-tests:
          context: legiti-variables
          filters:
            branches:
              ignore:
                - main
  deploy:
    jobs:
      - deploy:
          context: legiti-variables
          name: Deploy
          filters:
            branches:
              only:
                - main
